version: "3.9"
services:
  db:
    image: postgres:14.8-alpine
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
    ports:
      - 5432:5432
    restart: unless-stopped

  api:
    build:
      context: .
    volumes:
      - ./src/:/src/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./src/.env
    command: >
      uvicorn server:app --host 0.0.0.0 --port 8000